baseURL = ""
languageCode = 'en-us'
title = 'CRYPTO'
paginate = 5
theme = 'PaperMod'

[params]
  title = "GLENNY - Professional Portfolio"
  description = "A professional portfolio website showcasing your work, skills, and contact information."
  keywords = ["portfolio", "software engineer", "web development"]
  author = "GLENNY"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "skills"
    name = "Skills"
    url = "/skills/"
    weight = 20
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 30
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 40